name: admin-ui-webhook
namespace: official
version: 1.1.2-4
author: Wazo Team
display_name: Webhook
min_wazo_version: 18.02
tags:
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-webhook
icon: gear
debian_depends:
  - wazo-webhookd-client-python3
