name: admin-ui-webhook
namespace: official
version: 0.0.1
author: Wazo Team
display_name: Webhook
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-webhook
debian_depends:
  - wazo-webhookd-client
