name: admin-ui-webhook
namespace: official
version: 1.1.2-2
author: Wazo Team
display_name: Webhook
min_wazo_version: 18.01
tags:
  - beta
  - application
homepage: https://github.com/wazo-pbx/wazo-admin-ui-webhook
debian_depends:
  - wazo-webhookd-client-python3
